language: node_js
sudo: false
node_js:
  - 10.0.0
  - 8.0
install:
  - yarn
script:
  - yarn test:ci

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
